# Generated by Django 6.0.5 on 2026-05-24 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_applied_for', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20)),
                ('photograph', models.FileField(upload_to='photographs/')),
                ('correspondence_address_line1', models.CharField(max_length=300)),
                ('correspondence_address_line2', models.CharField(blank=True, default='', max_length=300)),
                ('permanent_address_line1', models.CharField(max_length=300)),
                ('permanent_address_line2', models.CharField(blank=True, default='', max_length=300)),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('extra_curricular', models.TextField(blank=True, default='')),
                ('why_suitable', models.TextField()),
                ('epf_member', models.BooleanField(default=False)),
                ('epf_number', models.CharField(blank=True, default='', max_length=22)),
                ('references', models.JSONField(blank=True, default=list)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('attach_10th', models.FileField(blank=True, null=True, upload_to='attachments/10th/')),
                ('attach_12th', models.FileField(blank=True, null=True, upload_to='attachments/12th/')),
                ('attach_diploma', models.FileField(blank=True, null=True, upload_to='attachments/diploma/')),
                ('attach_graduation', models.FileField(blank=True, null=True, upload_to='attachments/graduation/')),
                ('attach_post_graduation', models.FileField(blank=True, null=True, upload_to='attachments/pg/')),
                ('attach_pan_card', models.FileField(blank=True, null=True, upload_to='attachments/pan/')),
                ('attach_aadhaar', models.FileField(blank=True, null=True, upload_to='attachments/aadhaar/')),
                ('attach_form16', models.FileField(blank=True, null=True, upload_to='attachments/form16/')),
                ('attach_last_salary', models.FileField(blank=True, null=True, upload_to='attachments/salary/')),
                ('attach_experience_certs', models.FileField(blank=True, null=True, upload_to='attachments/experience/')),
                ('attach_fitness_cert', models.FileField(blank=True, null=True, upload_to='attachments/fitness/')),
                ('attach_photos', models.FileField(blank=True, null=True, upload_to='attachments/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Application',
                'verbose_name_plural': 'Staff Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10th', '10th Marksheet + Certificate'), ('12th', '12th Marksheet + Certificate'), ('diploma', 'Diploma Marksheets + Certificate'), ('graduation', 'Graduation Marksheets + Degree'), ('pg', 'Post Graduation Marksheets + Degree'), ('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('form16', 'Form 16'), ('salary', 'Last Salary Certificate'), ('experience', 'Experience Certificate'), ('fitness', 'Fitness Certificate'), ('photo', 'Latest Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='additional_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='recruitment.staffapplication')),
            ],
            options={
                'verbose_name': 'Staff Application Document',
                'verbose_name_plural': 'Staff Application Documents',
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
    ]
